export type ReportingModuleGroup = "Mantenimiento" | "Inventario";

export type ReportingLoader =
  | "standard"
  | "warehouse-documents"
  | "reservations";

export type ReportingModule = {
  key: string;
  title: string;
  shortTitle: string;
  description: string;
  icon: string;
  group: ReportingModuleGroup;
  routeName: string;
  endpoint: string;
  loader?: ReportingLoader;
  /** Los catálogos son una fotografía actual; no se les fuerza una fecha ficticia. */
  snapshot?: boolean;
  serverDateParams?: { from: string; to: string };
  requestParams?: Record<string, string>;
  dateFields: string[];
  titleFields: string[];
  statusFields: string[];
  categoryFields: string[];
  valueFields: string[];
  ownerFields?: string[];
  valueLabel?: string;
};

const auditDates = ["updated_at", "created_at"];
const auditOwner = ["updated_by", "created_by", "usuario", "responsable"];
const commonStatus = ["estado", "status", "estado_workflow"];

/**
 * Catálogo de fuentes del Centro de Informes.
 *
 * Incluye todos los módulos de negocio que hoy aparecen activos en el menú de
 * producción. Se excluyen seguridad, manuales y los demás dashboards porque no
 * representan un proceso operativo que deba contarse de nuevo dentro de
 * Reportería. Los catálogos (sucursales, bodegas, marcas...) también quedaron
 * fuera: son tablas de referencia, no actividad del período.
 */
export const REPORTING_MODULES: ReportingModule[] = [
  {
    key: "work-orders",
    title: "Órdenes de trabajo",
    shortTitle: "OT",
    description: "Seguimiento de órdenes de mantenimiento, su estado y carga operativa.",
    icon: "mdi-clipboard-text-clock-outline",
    group: "Mantenimiento",
    routeName: "work-orders",
    endpoint: "/kpi_maintenance/work-orders",
    serverDateParams: { from: "fecha_desde", to: "fecha_hasta" },
    dateFields: ["fecha", "started_at", "created_at"],
    titleFields: ["code", "codigo", "title", "descripcion"],
    statusFields: ["status", "estado_workflow", "estado"],
    categoryFields: ["maintenance_kind", "tipo_mantenimiento", "prioridad"],
    valueFields: ["costo_total", "total"],
    ownerFields: ["responsable_nombre", "created_by", "updated_by"],
    valueLabel: "Costo registrado",
  },
  {
    key: "project-work-orders",
    title: "Órdenes de trabajo de proyecto",
    shortTitle: "OT Proyecto",
    description: "Avance y estado de trabajos especiales ejecutados como proyecto.",
    icon: "mdi-clipboard-flow-outline",
    group: "Mantenimiento",
    routeName: "work-orders-proyecto",
    endpoint: "/kpi_maintenance/work-orders",
    serverDateParams: { from: "fecha_desde", to: "fecha_hasta" },
    requestParams: { maintenance_kind: "PROYECTO" },
    dateFields: ["fecha", "started_at", "created_at"],
    titleFields: ["code", "codigo", "title", "proyecto_nombre", "descripcion"],
    statusFields: ["status", "estado_workflow", "estado"],
    categoryFields: ["maintenance_kind", "proyecto_empresa", "prioridad"],
    valueFields: ["costo_total", "total_mano_obra", "total"],
    ownerFields: ["responsable_nombre", "created_by", "updated_by"],
    valueLabel: "Valor registrado",
  },
  {
    key: "generation-units",
    title: "Unidades de generación",
    shortTitle: "U. generación",
    description: "Estado actual y distribución de las unidades que generan energía.",
    icon: "mdi-engine-outline",
    group: "Mantenimiento",
    routeName: "unidades-generacion",
    endpoint: "/kpi_maintenance/equipos",
    requestParams: { grupo: "GENERACION" },
    snapshot: true,
    dateFields: auditDates,
    titleFields: ["codigo", "nombre", "descripcion"],
    statusFields: ["estado_funcionamiento", "status", "estado"],
    categoryFields: ["tipo_equipo_nombre", "equipo_tipo_nombre", "marca_nombre"],
    valueFields: ["horometro_actual", "horometro"],
    ownerFields: auditOwner,
    valueLabel: "Horómetro acumulado",
  },
  {
    key: "equipment",
    title: "Otros equipos",
    shortTitle: "Equipos",
    description: "Inventario operativo de equipos que no pertenecen a generación ni proyectos.",
    icon: "mdi-tools",
    group: "Mantenimiento",
    routeName: "equipos",
    endpoint: "/kpi_maintenance/equipos",
    requestParams: { grupo: "RESTO" },
    snapshot: true,
    dateFields: auditDates,
    titleFields: ["codigo", "nombre", "descripcion"],
    statusFields: ["estado_funcionamiento", "status", "estado"],
    categoryFields: ["tipo_equipo_nombre", "equipo_tipo_nombre", "marca_nombre"],
    valueFields: ["horometro_actual", "horometro"],
    ownerFields: auditOwner,
    valueLabel: "Horómetro acumulado",
  },
  {
    key: "projects",
    title: "Proyectos",
    shortTitle: "Proyectos",
    description: "Proyectos registrados como unidad de seguimiento dentro de mantenimiento.",
    icon: "mdi-office-building-cog-outline",
    group: "Mantenimiento",
    routeName: "proyectos",
    endpoint: "/kpi_maintenance/equipos",
    requestParams: { grupo: "PROYECTOS" },
    snapshot: true,
    dateFields: auditDates,
    titleFields: ["codigo", "nombre", "descripcion"],
    statusFields: ["estado_funcionamiento", "status", "estado"],
    categoryFields: ["tipo_equipo_nombre", "equipo_tipo_nombre", "location_nombre"],
    valueFields: ["horometro_actual", "horometro"],
    ownerFields: auditOwner,
    valueLabel: "Avance registrado",
  },
  {
    key: "schedules",
    title: "Programaciones",
    shortTitle: "Programación",
    description: "Actividades planificadas y cumplimiento de fechas de mantenimiento.",
    icon: "mdi-calendar-clock-outline",
    group: "Mantenimiento",
    routeName: "programaciones",
    endpoint: "/kpi_maintenance/programaciones",
    dateFields: ["fecha_programada", "fecha_inicio", "created_at"],
    titleFields: ["codigo", "titulo", "plan_nombre", "descripcion"],
    statusFields: commonStatus,
    categoryFields: ["tipo", "frecuencia_tipo", "equipo_nombre"],
    valueFields: ["horas_estimadas", "duracion_horas"],
    ownerFields: auditOwner,
    valueLabel: "Horas programadas",
  },
  {
    key: "alerts",
    title: "Alertas",
    shortTitle: "Alertas",
    description: "Alertas generadas, su criticidad y atención durante el período.",
    icon: "mdi-alert-decagram-outline",
    group: "Mantenimiento",
    routeName: "alertas",
    endpoint: "/kpi_maintenance/alertas",
    dateFields: ["fecha_alerta", "triggered_at", "created_at"],
    titleFields: ["titulo", "title", "codigo", "descripcion"],
    statusFields: commonStatus,
    categoryFields: ["criticidad", "prioridad", "categoria", "origen"],
    valueFields: ["valor_actual", "valor"],
    ownerFields: ["responsable_nombre", ...auditOwner],
    valueLabel: "Valor observado",
  },
  {
    key: "templates",
    title: "Plantillas",
    shortTitle: "Plantillas",
    description: "Plantillas y listas de verificación disponibles para ejecutar trabajos.",
    icon: "mdi-clipboard-list-outline",
    group: "Mantenimiento",
    routeName: "inteligencia-procedimientos",
    endpoint: "/kpi_maintenance/inteligencia/procedimientos",
    snapshot: true,
    dateFields: auditDates,
    titleFields: ["codigo", "nombre", "titulo", "descripcion"],
    statusFields: commonStatus,
    categoryFields: ["tipo_proceso", "tipo_mantenimiento", "frecuencia_tipo"],
    valueFields: ["frecuencia_horas", "duracion_estimada"],
    ownerFields: auditOwner,
    valueLabel: "Frecuencia configurada",
  },
  {
    key: "lubricant-analysis",
    title: "Análisis de lubricante",
    shortTitle: "Lubricantes",
    description: "Muestras, resultados y condición diagnosticada de los lubricantes.",
    icon: "mdi-oil-temperature",
    group: "Mantenimiento",
    routeName: "inteligencia-analisis-lubricante",
    endpoint: "/kpi_maintenance/inteligencia/analisis-lubricante",
    dateFields: ["fecha_muestra", "fecha_reporte", "created_at"],
    titleFields: ["numero_muestra", "codigo", "lubricante", "equipo_nombre"],
    statusFields: ["estado_diagnostico", "condicion", "status"],
    categoryFields: ["compartimento_principal", "marca_lubricante", "equipo_nombre"],
    valueFields: ["horas_lubricante", "horas_equipo"],
    ownerFields: auditOwner,
    valueLabel: "Horas registradas",
  },
  {
    key: "materials",
    title: "Materiales",
    shortTitle: "Materiales",
    description: "Catálogo de repuestos, insumos y servicios utilizados por la operación.",
    icon: "mdi-package-variant-closed",
    group: "Inventario",
    routeName: "productos",
    endpoint: "/kpi_inventory/productos",
    snapshot: true,
    dateFields: auditDates,
    titleFields: ["codigo", "nombre", "descripcion"],
    statusFields: commonStatus,
    categoryFields: ["categoria_nombre", "linea_nombre", "marca_nombre"],
    valueFields: ["stock_total", "costo_promedio", "ultimo_costo"],
    ownerFields: auditOwner,
    valueLabel: "Valor de referencia",
  },
  {
    key: "warehouse-stock",
    title: "Stock por bodega",
    shortTitle: "Stock bodega",
    description: "Disponibilidad actual de cada material en las diferentes bodegas.",
    icon: "mdi-warehouse",
    group: "Inventario",
    routeName: "stock-bodega",
    endpoint: "/kpi_inventory/stock-bodega",
    snapshot: true,
    dateFields: auditDates,
    titleFields: ["producto_codigo", "producto_nombre", "codigo", "nombre"],
    statusFields: ["estado_stock", "status", "estado"],
    categoryFields: ["bodega_nombre", "bodega_codigo", "categoria_nombre"],
    valueFields: ["stock_actual", "cantidad", "stock"],
    ownerFields: auditOwner,
    valueLabel: "Unidades disponibles",
  },
  {
    key: "kardex",
    title: "Kardex",
    shortTitle: "Kardex",
    description: "Trazabilidad de entradas y salidas que modificaron las existencias.",
    icon: "mdi-swap-horizontal-bold",
    group: "Inventario",
    routeName: "kardex",
    endpoint: "/kpi_inventory/kardex/documentos/lista",
    loader: "warehouse-documents",
    serverDateParams: { from: "desde", to: "hasta" },
    dateFields: ["fecha_movimiento", "created_at"],
    titleFields: ["numero_documento", "codigo", "referencia"],
    statusFields: ["estado", "tipo_movimiento", "status"],
    categoryFields: ["tipo_movimiento", "origen", "bodega_nombre"],
    valueFields: ["total_cantidad", "total_items"],
    ownerFields: ["created_by", "usuario"],
    valueLabel: "Unidades movilizadas",
  },
  {
    key: "warehouse-income",
    title: "Ingresos de bodega",
    shortTitle: "Ingresos",
    description: "Documentos que aumentaron el stock de las bodegas.",
    icon: "mdi-tray-arrow-down",
    group: "Inventario",
    routeName: "ingresos-bodega",
    endpoint: "/kpi_inventory/kardex/documentos/lista",
    loader: "warehouse-documents",
    serverDateParams: { from: "desde", to: "hasta" },
    requestParams: { tipo_movimiento: "INGRESO" },
    dateFields: ["fecha_movimiento", "created_at"],
    titleFields: ["numero_documento", "codigo", "referencia"],
    statusFields: ["estado", "origen", "status"],
    categoryFields: ["origen", "bodega_nombre", "tipo_documento_label"],
    valueFields: ["total_cantidad", "total_items"],
    ownerFields: ["created_by", "usuario"],
    valueLabel: "Unidades ingresadas",
  },
  {
    key: "warehouse-output",
    title: "Egresos de bodega",
    shortTitle: "Egresos",
    description: "Documentos que disminuyeron el stock y su origen operativo.",
    icon: "mdi-tray-arrow-up",
    group: "Inventario",
    routeName: "egresos-bodega",
    endpoint: "/kpi_inventory/kardex/documentos/lista",
    loader: "warehouse-documents",
    serverDateParams: { from: "desde", to: "hasta" },
    requestParams: { tipo_movimiento: "SALIDA" },
    dateFields: ["fecha_movimiento", "created_at"],
    titleFields: ["numero_documento", "codigo", "referencia"],
    statusFields: ["estado", "origen", "status"],
    categoryFields: ["origen", "bodega_nombre", "tipo_documento_label"],
    valueFields: ["total_cantidad", "total_items"],
    ownerFields: ["created_by", "usuario"],
    valueLabel: "Unidades despachadas",
  },
  {
    key: "warehouse-transfers",
    title: "Transferencias de bodega",
    shortTitle: "Transferencias",
    description: "Movimientos entre bodegas, su estado y volumen trasladado.",
    icon: "mdi-truck-fast-outline",
    group: "Inventario",
    routeName: "transferencias-bodega",
    endpoint: "/kpi_inventory/transferencias-bodega",
    serverDateParams: { from: "desde", to: "hasta" },
    dateFields: ["fecha_transferencia", "fecha", "created_at"],
    titleFields: ["codigo", "numero_documento", "referencia"],
    statusFields: commonStatus,
    categoryFields: ["bodega_origen_nombre", "bodega_destino_nombre", "tipo"],
    valueFields: ["total_cantidad", "cantidad_total", "total_items"],
    ownerFields: auditOwner,
    valueLabel: "Unidades transferidas",
  },
  {
    key: "warehouse-reservations",
    title: "Reservas de bodega",
    shortTitle: "Reservas",
    description: "Material solicitado por las OT, entregado o liberado por bodega.",
    icon: "mdi-package-variant",
    group: "Inventario",
    routeName: "reservas-bodega",
    endpoint: "/kpi_maintenance/work-orders/reservations",
    loader: "reservations",
    snapshot: true,
    dateFields: ["fecha_reserva", "created_at", "updated_at"],
    titleFields: ["producto_codigo", "producto_nombre", "work_order_code", "codigo_ot"],
    statusFields: ["estado", "status"],
    categoryFields: ["bodega_nombre", "work_order_code", "equipo_nombre"],
    valueFields: ["cantidad_reservada_activa", "cantidad_solicitada", "cantidad_pendiente"],
    ownerFields: auditOwner,
    valueLabel: "Unidades reservadas",
  },
  {
    key: "purchase-orders",
    title: "Órdenes de compra",
    shortTitle: "O. compra",
    description: "Compras emitidas, recepción y valor gestionado con proveedores.",
    icon: "mdi-cart-arrow-down",
    group: "Inventario",
    routeName: "ordenes-compra",
    endpoint: "/kpi_inventory/ordenes-compra",
    serverDateParams: { from: "desde", to: "hasta" },
    dateFields: ["fecha_emision", "fecha", "created_at"],
    titleFields: ["codigo", "numero", "proveedor_nombre"],
    statusFields: commonStatus,
    categoryFields: ["proveedor_nombre", "tipo_compra", "bodega_nombre"],
    valueFields: ["total", "total_final", "subtotal"],
    ownerFields: ["emitido_por_nombre", ...auditOwner],
    valueLabel: "Valor comprado",
  },
  {
    key: "service-orders",
    title: "Órdenes de servicio",
    shortTitle: "O. servicio",
    description: "Servicios contratados a proveedores y confirmación de ejecución.",
    icon: "mdi-file-document-wrench-outline",
    group: "Inventario",
    routeName: "ordenes-servicio",
    endpoint: "/kpi_inventory/ordenes-servicio",
    serverDateParams: { from: "desde", to: "hasta" },
    dateFields: ["fecha_emision", "fecha", "created_at"],
    titleFields: ["codigo", "numero", "proveedor_nombre"],
    statusFields: commonStatus,
    categoryFields: ["proveedor_nombre", "servicio_realizado", "lugar_entrega"],
    valueFields: ["total", "total_final", "subtotal"],
    ownerFields: ["emitido_por_nombre", ...auditOwner],
    valueLabel: "Valor contratado",
  },
];

export const REPORTING_MODULE_GROUPS: ReportingModuleGroup[] = [
  "Mantenimiento",
  "Inventario",
];

export function getReportingModule(
  key: string | null | undefined,
): ReportingModule {
  return REPORTING_MODULES.find((item) => item.key === key) ?? REPORTING_MODULES[0]!;
}
